repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.53.0'
    hooks:
      - id: eslint
  - repo: local
    hooks:
      - id: laravel-pint
        name: laravel-pint
        entry: bash -c './vendor/bin/pint'
        language: system
        types: [ php ]
        pass_filenames: false
